-- BIMVORA 3-level taxonomy: Department -> Product Category -> Product Type.
-- Adds product metadata columns and seeds the product-type level (L3).

-- 1) Product metadata used by the enhanced product page + filters.
alter table public.products
  add column if not exists manufacturer text,
  add column if not exists cad_formats text[] not null default '{}',
  add column if not exists has_datasheet boolean not null default false;

create index if not exists products_manufacturer_idx
  on public.products (manufacturer);

-- 2) Align HVAC product category naming and retire the AHU category
--    (air-handling content now lives under other categories/types).
update public.categories set name = 'Chillers' where slug = 'chillers';
update public.categories set name = 'Heat Pumps' where slug = 'heat-pumps';
update public.categories set name = 'FCU – Fan Coil Units' where slug = 'fcu';
update public.categories set is_active = false where slug = 'ahu-cta-uta';

-- 3) Product types (level 3). Slugs mirror the app helper:
--    `${parent_slug}-${kebab(name)}` to stay globally unique across departments.
insert into public.categories (slug, name, description, parent_id, discipline, sort_order, is_active)
select
  p.slug || '-' ||
    regexp_replace(regexp_replace(lower(t.name), '[^a-z0-9]+', '-', 'g'), '(^-|-$)', '', 'g') as slug,
  t.name,
  t.name || ' Revit families under ' || p.name || '.',
  p.id,
  p.discipline,
  p.sort_order * 100 + t.ord,
  true
from (values
  -- HVAC / Mechanical
  ('chillers','Air Cooled Chiller',1),
  ('chillers','Water Cooled Chiller',2),
  ('chillers','Scroll Chiller',3),
  ('chillers','Screw Chiller',4),
  ('chillers','Centrifugal Chiller',5),
  ('fcu','2-Pipe FCU',1),
  ('fcu','4-Pipe FCU',2),
  ('fcu','Ceiling FCU',3),
  ('fcu','Ducted FCU',4),
  ('fcu','Cassette FCU',5),
  ('heat-pumps','Air Source Heat Pump',1),
  ('heat-pumps','Water Source Heat Pump',2),
  ('heat-pumps','Ground Source Heat Pump',3),
  ('heat-pumps','VRF Outdoor Unit',4),
  ('heat-pumps','Monobloc Heat Pump',5),
  ('fans','Axial Fan',1),
  ('fans','Centrifugal Fan',2),
  ('fans','Exhaust Fan',3),
  ('fans','Inline Fan',4),
  ('fans','Roof Fan',5),
  ('fans','Smoke Extraction Fan',6),
  ('diffusers-grilles','Ceiling Diffuser',1),
  ('diffusers-grilles','Linear Diffuser',2),
  ('diffusers-grilles','Jet Diffuser',3),
  ('diffusers-grilles','Supply Grille',4),
  ('diffusers-grilles','Return Grille',5),
  ('diffusers-grilles','Exhaust Grille',6),
  ('ducts-accessories','Rectangular Duct',1),
  ('ducts-accessories','Circular Duct',2),
  ('ducts-accessories','Flexible Duct',3),
  ('ducts-accessories','Duct Connector',4),
  ('ducts-accessories','Duct Insulation',5),
  ('ducts-accessories','Access Door',6),
  ('dampers','Volume Control Damper',1),
  ('dampers','Fire Damper',2),
  ('dampers','Smoke Damper',3),
  ('dampers','Motorized Damper',4),
  ('dampers','Backdraft Damper',5),
  ('hvac-pumps','Inline Pump',1),
  ('hvac-pumps','End Suction Pump',2),
  ('hvac-pumps','Twin Pump',3),
  ('hvac-pumps','Primary Pump',4),
  ('hvac-pumps','Secondary Pump',5),
  ('hvac-valves','2-Way Valve',1),
  ('hvac-valves','3-Way Valve',2),
  ('hvac-valves','Butterfly Valve',3),
  ('hvac-valves','Ball Valve',4),
  ('hvac-valves','Globe Valve',5),
  ('hvac-valves','Check Valve',6),
  ('hvac-valves','PICV',7),
  ('hvac-piping','Steel Pipe',1),
  ('hvac-piping','Copper Pipe',2),
  ('hvac-piping','PPR Pipe',3),
  ('hvac-piping','HDPE Pipe',4),
  ('hvac-piping','Insulated Pipe',5),
  ('hvac-piping','Chilled Water Pipe',6),
  -- Plumbing
  ('cold-hot-water','PPR Water Pipe',1),
  ('cold-hot-water','PEX Water Pipe',2),
  ('cold-hot-water','Copper Water Pipe',3),
  ('cold-hot-water','Manifold',4),
  ('cold-hot-water','Pressure Reducing Set',5),
  ('cold-hot-water','Water Meter',6),
  ('sanitary-fixtures','WC',1),
  ('sanitary-fixtures','Wash Basin',2),
  ('sanitary-fixtures','Shower',3),
  ('sanitary-fixtures','Sink',4),
  ('sanitary-fixtures','Urinal',5),
  ('sanitary-fixtures','Bidet',6),
  ('drainage-waste','PVC Drainage Pipe',1),
  ('drainage-waste','Floor Drain',2),
  ('drainage-waste','Gully Trap',3),
  ('drainage-waste','Vent Pipe',4),
  ('drainage-waste','Cleanout',5),
  ('drainage-waste','Grease Trap',6),
  ('water-heaters','Electric Water Heater',1),
  ('water-heaters','Gas Water Heater',2),
  ('water-heaters','Storage Cylinder',3),
  ('water-heaters','Instantaneous Heater',4),
  ('water-heaters','Solar Water Heater',5),
  ('tanks','Storage Tank',1),
  ('tanks','Break Tank',2),
  ('tanks','Expansion Tank',3),
  ('tanks','GRP Sectional Tank',4),
  ('tanks','Pressure Vessel',5),
  ('plumbing-pumps','Booster Pump',1),
  ('plumbing-pumps','Sump Pump',2),
  ('plumbing-pumps','Submersible Pump',3),
  ('plumbing-pumps','Transfer Pump',4),
  ('plumbing-pumps','Circulator Pump',5),
  ('plumbing-valves','Gate Valve',1),
  ('plumbing-valves','Ball Valve',2),
  ('plumbing-valves','Check Valve',3),
  ('plumbing-valves','Pressure Reducing Valve',4),
  ('plumbing-valves','Float Valve',5),
  ('plumbing-valves','Mixing Valve',6),
  ('plumbing-accessories','Pipe Support',1),
  ('plumbing-accessories','Air Vent',2),
  ('plumbing-accessories','Strainer',3),
  ('plumbing-accessories','Flexible Connector',4),
  ('plumbing-accessories','Trap',5),
  -- Clean Room / Pharmaceutical
  ('hepa-filters','Terminal HEPA Filter',1),
  ('hepa-filters','Ducted HEPA Filter',2),
  ('hepa-filters','HEPA Filter Box',3),
  ('hepa-filters','ULPA Filter',4),
  ('hepa-filters','Bag-In Bag-Out Filter',5),
  ('ffu','2x2 FFU',1),
  ('ffu','2x4 FFU',2),
  ('ffu','Room-Side Replaceable FFU',3),
  ('ffu','EC Motor FFU',4),
  ('laf','Horizontal LAF',1),
  ('laf','Vertical LAF',2),
  ('laf','LAF Trolley',3),
  ('laf','LAF Canopy',4),
  ('clean-room-ahu','Hygienic AHU',1),
  ('clean-room-ahu','Recirculation AHU',2),
  ('clean-room-ahu','Make-Up Air AHU',3),
  ('clean-room-ahu','Ducted AHU',4),
  ('pass-box','Static Pass Box',1),
  ('pass-box','Dynamic Pass Box',2),
  ('pass-box','Ventilated Pass Box',3),
  ('pass-box','BioSafety Pass Box',4),
  ('air-shower','Personnel Air Shower',1),
  ('air-shower','Material Air Shower',2),
  ('air-shower','Tunnel Air Shower',3),
  ('air-shower','Cargo Air Shower',4),
  ('clean-room-doors','Single Leaf Door',1),
  ('clean-room-doors','Double Leaf Door',2),
  ('clean-room-doors','Sliding Door',3),
  ('clean-room-doors','Vision Panel Door',4),
  ('clean-room-doors','Interlock Door',5),
  ('sas-personnel-material','SAS Personnel',1),
  ('sas-personnel-material','SAS Material',2),
  ('sas-personnel-material','Airlock',3),
  ('sas-personnel-material','De-Gowning SAS',4),
  ('gowning-room','Gowning Bench',1),
  ('gowning-room','SS Storage Locker',2),
  ('gowning-room','Garment Rack',3),
  ('gowning-room','Cross-Over Bench',4),
  ('gowning-room','Step-Over Bench',5)
) as t(parent_slug, name, ord)
join public.categories p on p.slug = t.parent_slug
on conflict (slug) do nothing;
